server:
  port: 9095
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cloud2023@
    url: jdbc:mysql://localhost:3306/lost_found?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    database: 3
    host: localhost
    port: 6379

default:
  avatar: "http://118.25.40.159:9090/lostfound/2024/04/24/fcc8d61be4e14ef7b85eb116571cbef3.png"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.hnust.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      hnust:
        mapper: debug
        service: info
        controller: info

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost

minio:
  accessKey: minio
  secretKey: minio123
  bucket: lostfound
  endpoint: http://118.25.40.159:9090
  readPath: http://118.25.40.159:9090

jwt:
  admin-secret-key: lost&found
  admin-ttl: 3600000
  admin-token-name: token

  user-secret-key: lost&found
  user-ttl: 3600000
  user-token-name: authentication